[GLOBAL]
mailUs = "AKIASWTWHVISO27R4S7R"
mailPa = "BIWnz2eaTb7DgUA1VdNWw3NX1jvlPjDoPPETy4CZIR01"
VERSION = "4.2.1"

[LOCAL] ;BD Local
;userDB= "root"
;passDB= "12345"
;serverDBEscritura= "localhost"
;serverDBLectura= "localhost"
;dataBaseDB= "hsbc"
;urlTokenSms = "https://micromsn-qa.dev-pruebas.com/Stage/sign-in-cognito"
;urlSendSms = "https://micromsn-qa.dev-pruebas.com/Stage/sendMessage"
;usernameTokenSms = "ecommerce_dev"
;passwordTokenSms = "#ZY$r7Aj6Bcx"
;urlOauth = "https://oauth.dev-pruebas.com/oauth/token?grant_type=password"
;authorizationOauth= "Basic SUtFX0hTQkM6V09nR3gzbXhwVFhZMEtSMWZX"
;urlApiAfiliados= "https://apiafiliadosqa.ikeasistencia.com:8443/Ike-Api/Mx/M/1/Load/Single/?Key-Id=IKE-069&key=WOgGx3mxpTXY0KR1fW"
;captchaPublic = "6LejznEqAAAAAJd9U61zCtTPxxH_whInqdeUmx_B"
;captchaSecret = "6LejznEqAAAAAHIpjnlDW52kPnMV1HmvaStdMzZm"
;ambiente = "2"

[QA] ;BD QA
userDB= "usrlockton_dev"
passDB= "I@DVcU$t59Y93Uad7gpY"
serverDBEscritura= "ecommerce-db-wr.dev-pruebas.com"
serverDBLectura= "ecommerce-db-wr.dev-pruebas.com"
dataBaseDB= "lockton_dev"
urlTokenSms = "https://micromsn-qa.dev-pruebas.com/Stage/sign-in-cognito"
urlSendSms = "https://micromsn-qa.dev-pruebas.com/Stage/sendMessage"
usernameTokenSms = "ecommerce_dev"
passwordTokenSms = "#ZY$r7Aj6Bcx"
urlOauth = "https://oauth.dev-pruebas.com/oauth/token?grant_type=password"
authorizationOauth= "Basic SUtFX0hTQkM6V09nR3gzbXhwVFhZMEtSMWZX"
urlApiAfiliados= "https://apiafiliadosqa.ikeasistencia.com:8443/Ike-Api/Mx/M/1/Load/Single/?Key-Id=IKE-069&key=WOgGx3mxpTXY0KR1fW"
captchaPublic = "6LcRhWMqAAAAANeCH1dlsLubRTA-nPfCQdl1_q5d"
captchaSecret = "6LcRhWMqAAAAAIoIP57480eCddTMmYLqhqwv1dEn"
ambiente= "1"

[PROD] ;BD Producción
;userDB= "locktonIke"
;passDB= "TUpm678.-"
;serverDBEscritura= "ike-db-ecommerce-prod.cluster-cut2e5vnrecv.us-east-2.rds.amazonaws.com"
;serverDBLectura= "ike-db-ecommerce-prod.cluster-ro-cut2e5vnrecv.us-east-2.rds.amazonaws.com"
;dataBaseDB= "lockton_prod"
;urlTokenSms = "https://micromsn.ikeasistencia.com/Prod/sign-in-cognito"
;urlSendSms = "https://micromsn.ikeasistencia.com/Prod/sendMessage"
;usernameTokenSms = "ecommerce_prod"
;passwordTokenSms = "t!O&F#0QrFCi"
;urlOauth = "https://oauth.dev-pruebas.com/oauth/token?grant_type=password"
;authorizationOauth= "Basic SUtFX0hTQkM6V09nR3gzbXhwVFhZMEtSMWZX"
;urlApiAfiliados= "https://apiafiliadosqa.ikeasistencia.com:8443/Ike-Api/Mx/M/1/Load/Single/?Key-Id=IKE-069&key=WOgGx3mxpTXY0KR1fW"
;captchaPublic = "6LfohWMqAAAAAFU0k1m4-KWC4OieM0gwSP9SQrIH"
;captchaSecret = "6LfohWMqAAAAAMBTmyL9tfZme-6BttBwN2tDoQ7B"
;ambiente= "0"