name: Deploy

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Copiar el contenido del repositorio con scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOSTQA }}
        username: ${{ secrets.USERNAMEQA }}
        port: ${{ secrets.PORTQA }}
        key: ${{ secrets.SSHKEYQA }}
        source: "ike-sitios-integrales-dev/*"
        target: "/var/www/ike-sitio-combosintegrales-dev"
        strip_components: 1
